travis:
  secure:
    BINSTAR_TOKEN: O1X82I0mcqmsGmp1zUj7R91XhFyNPTZkcm0F22ghytKwg3pjhdEsK+yBDyUiXmpGMs/zSySX6/KpqBL46cezrTrPcGzR3r0tIIyKo5J179sEQWTF8GaVxzoj1qy++dPORakupOLjYdhP6Vwtl6UaxS/ccIS/hc6SW+RB1kMWA8Wd4GsusxHohkMBR4cUj/PT/9poULo/I4+/H5Gu412IkuHFCDg0SteIvJFVCHMECL+F+z+j3gv060Acyt42EcZliLpwNHlRJM7Q9z5cd4MzilI6dpARCccd/zkOr2YZDA1XSAnodBs1PDj8bK+2jpwHb98K8BStdR8ppQZST2pavV3E+Jrwc5jYYVVFL/VaDu8PSaxNitMBp45RRCyXHGnmLMgL0BHPPA5o+hwMXoNpgrCzqHvgScIPyxqTwWxK3W7YQqFXaxxlFteGqbh2OdWAKAzlfiuuD8+4wyDi1fakFYSGVO3h/UmI6SX+y8BDoLGCX7/dO9CMFUzVgk4thxIUe0rdGRKsCcqKUMZcWT0CVvcO4cwGEofqO9r5k+D9IB08pDEuS1Uq1ZkGhrjYEMQ/gg6+ovprpnqkUlpRXe0NxJas78lJsecAULfzkjywfSY4FVV00svuQnYVh3+2j3gWoJmddSmBRPjA9FQAzrDrCGZgkbew/VqY+EnyMgj2K3w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
